"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os

from setuptools import setup

APP = ['MainGUI.py']
APP_NAME = "Android Toolgy"
OPTIONS = {
    'includes': ['wx', 'pubsub', 'subprocess', 'os'],
    'iconfile': 'icon-256x256.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
    }
}

BASEDIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILES = ['config.xml', 'icon-256x256.icns']
for root, dirs, files in os.walk(BASEDIR):
    for file in files:
        finalPath = os.path.join(root, file)
        if '__pycache__' in finalPath:
            continue
        if '.idea' in finalPath:
            continue
        if '__init__.py' in finalPath:
            continue
        if finalPath.endswith('.py'):
            DATA_FILES.append(finalPath)

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
